# Generated by Django 4.2.5 on 2023-10-02 14:44

from django.db import migrations, models
import django.db.models.deletion
import rooms.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=15)),
                ('available', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(help_text='The date must be at least one day later.', validators=[rooms.models.validate_datetime_in_future])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_rooms', to='courses.course')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
