# Generated by Django 4.2.5 on 2023-10-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='caption',
            field=models.CharField(default=None, max_length=255, verbose_name='التسمية التوضيحية'),
            preserve_default=False,
        ),
    ]
