# Generated by Django 4.2.5 on 2024-04-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursecomment_user_modulecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulecomment',
            options={'ordering': ['-created']},
        ),
    ]
