# Generated by Django 4.2.5 on 2024-04-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='users_like',
        ),
    ]
