# Generated by Django 4.2.5 on 2023-10-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, help_text='يمكنك الكتابة عن نفسك مثل: مهاراتك وخبراتك ... الخ.', null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='defaults/default.jpg', upload_to='accounts/images', verbose_name='صورة الملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='رقم الهاتف'),
        ),
    ]
