# Generated by Django 4.2.5 on 2023-10-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_description_alter_customuser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='التعليم'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='السكن'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المهارات'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, help_text='يمكنك كتابة أي شئ تريده هنا.', null=True, verbose_name='الوصف'),
        ),
    ]
