# Generated by Django 4.2.5 on 2023-10-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='user',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='البريد الإلكتروني'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcomment',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='الإسم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
    ]
